import logging

logger = logging.getLogger('main_logs')
logger.setLevel(logging.DEBUG)
fh = logging.FileHandler('logging.log')
fh.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.ERROR)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
ch.setFormatter(formatter)
logger.addHandler(fh)
logger.addHandler(ch)

logclass = logging.getLogger('class_logs')
logclass.setLevel(logging.CRITICAL)
fh2 = logging.FileHandler('class.log')
fh2.setLevel(logging.DEBUG)
ch2 = logging.StreamHandler()
ch2.setLevel(logging.ERROR)
fh2.setFormatter(formatter)
ch2.setFormatter(formatter)
logclass.addHandler(fh2)
logclass.addHandler(ch2)